import libs = libraylib%lib{raylib}

# rexm calls text functions (LoadTextLines, TextIsEqual etc.) from rtext.
#
./: exe{rexm}: include = $($libs: libraylib.module_text)
exe{rexm}: c{rexm} $libs testscript

# rexm selects platform report names via PLATFORM_DESKTOP + OS macros.
#
c.poptions += -DPLATFORM_DESKTOP
