intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

# Optional external GLFW (cppget package name is glfw).
#
if $config.libraylib.external_glfw
  import impl_libs += glfw%lib{glfw}

# ---------------------------------------------------------------------------
# Graphics API
# ---------------------------------------------------------------------------
#
switch $config.libraylib.graphics
{
  case 'opengl-4.3'
    graphics_api = GRAPHICS_API_OPENGL_43
  case 'opengl-3.3'
    graphics_api = GRAPHICS_API_OPENGL_33
  case 'opengl-2.1'
    graphics_api = GRAPHICS_API_OPENGL_21
  case 'opengl-1.1'
    graphics_api = GRAPHICS_API_OPENGL_11
  case 'opengl-es2'
    graphics_api = GRAPHICS_API_OPENGL_ES2
  case 'opengl-es3'
    graphics_api = GRAPHICS_API_OPENGL_ES3
  case 'software'
    graphics_api = GRAPHICS_API_OPENGL_SOFTWARE
  default
    fail "invalid config.libraylib.graphics value \
'$config.libraylib.graphics' (expected opengl-4.3, opengl-3.3, \
opengl-2.1, opengl-1.1, opengl-es2, opengl-es3, or software)"
}

# ---------------------------------------------------------------------------
# Sources: always rcore (+ rglfw unless external GLFW). Optional modules.
# ---------------------------------------------------------------------------
#
lib{raylib}: {h}{raylib raymath rlgl rcamera config rgestures} \
             {c}{rcore} \
             $impl_libs $intf_libs

lib{raylib}: c{rshapes}:   include = $config.libraylib.module_shapes
lib{raylib}: c{rtextures}: include = $config.libraylib.module_textures
lib{raylib}: c{rtext}:     include = $config.libraylib.module_text
lib{raylib}: c{rmodels}:   include = $config.libraylib.module_models
lib{raylib}: c{raudio}:    include = $config.libraylib.module_audio
lib{raylib}: c{rglfw}:     include = (!$config.libraylib.external_glfw)

# Platform backends and vendored third-party code are #included, not compiled
# as separate translation units. Use file{**} so Objective-C (.m) GLFW sources
# and other non-.c/.h assets are distributed (required for macOS).
#
lib{raylib}: platforms/file{**}: include = adhoc
lib{raylib}: external/file{**}: include = adhoc

# ---------------------------------------------------------------------------
# Build options
# ---------------------------------------------------------------------------
#
c.poptions =+ "-I$src_base"

if! $config.libraylib.external_glfw
  c.poptions =+ "-I$src_base/external/glfw/include"

c.poptions += -DPLATFORM_DESKTOP_GLFW "-D$graphics_api"

# Drive all SUPPORT_* / RLGL_* flags explicitly (defaults match config.h).
# EXTERNAL_CONFIG_FLAGS disables the defaults block in config.h.
#
c.poptions += -DEXTERNAL_CONFIG_FLAGS

# Modules
#
c.poptions += ($config.libraylib.module_shapes   ? -DSUPPORT_MODULE_RSHAPES=1   : -DSUPPORT_MODULE_RSHAPES=0)
c.poptions += ($config.libraylib.module_textures ? -DSUPPORT_MODULE_RTEXTURES=1 : -DSUPPORT_MODULE_RTEXTURES=0)
c.poptions += ($config.libraylib.module_text     ? -DSUPPORT_MODULE_RTEXT=1     : -DSUPPORT_MODULE_RTEXT=0)
c.poptions += ($config.libraylib.module_models   ? -DSUPPORT_MODULE_RMODELS=1   : -DSUPPORT_MODULE_RMODELS=0)
c.poptions += ($config.libraylib.module_audio    ? -DSUPPORT_MODULE_RAUDIO=1    : -DSUPPORT_MODULE_RAUDIO=0)

# rcore features
#
c.poptions += ($config.libraylib.tracelog              ? -DSUPPORT_TRACELOG=1              : -DSUPPORT_TRACELOG=0)
c.poptions += ($config.libraylib.camera_system         ? -DSUPPORT_CAMERA_SYSTEM=1         : -DSUPPORT_CAMERA_SYSTEM=0)
c.poptions += ($config.libraylib.gestures_system       ? -DSUPPORT_GESTURES_SYSTEM=1       : -DSUPPORT_GESTURES_SYSTEM=0)
c.poptions += ($config.libraylib.rprand_generator      ? -DSUPPORT_RPRAND_GENERATOR=1      : -DSUPPORT_RPRAND_GENERATOR=0)
c.poptions += ($config.libraylib.mouse_gestures        ? -DSUPPORT_MOUSE_GESTURES=1        : -DSUPPORT_MOUSE_GESTURES=0)
c.poptions += ($config.libraylib.ssh_keyboard_rpi      ? -DSUPPORT_SSH_KEYBOARD_RPI=1      : -DSUPPORT_SSH_KEYBOARD_RPI=0)
c.poptions += ($config.libraylib.winmm_highres_timer   ? -DSUPPORT_WINMM_HIGHRES_TIMER=1   : -DSUPPORT_WINMM_HIGHRES_TIMER=0)
c.poptions += ($config.libraylib.busy_wait_loop        ? -DSUPPORT_BUSY_WAIT_LOOP=1        : -DSUPPORT_BUSY_WAIT_LOOP=0)
c.poptions += ($config.libraylib.partialbusy_wait_loop ? -DSUPPORT_PARTIALBUSY_WAIT_LOOP=1 : -DSUPPORT_PARTIALBUSY_WAIT_LOOP=0)
c.poptions += ($config.libraylib.screen_capture        ? -DSUPPORT_SCREEN_CAPTURE=1        : -DSUPPORT_SCREEN_CAPTURE=0)
c.poptions += ($config.libraylib.compression_api       ? -DSUPPORT_COMPRESSION_API=1       : -DSUPPORT_COMPRESSION_API=0)
c.poptions += ($config.libraylib.automation_events     ? -DSUPPORT_AUTOMATION_EVENTS=1     : -DSUPPORT_AUTOMATION_EVENTS=0)
c.poptions += ($config.libraylib.custom_frame_control  ? -DSUPPORT_CUSTOM_FRAME_CONTROL=1  : -DSUPPORT_CUSTOM_FRAME_CONTROL=0)
c.poptions += ($config.libraylib.clipboard_image       ? -DSUPPORT_CLIPBOARD_IMAGE=1       : -DSUPPORT_CLIPBOARD_IMAGE=0)

# rlgl
#
c.poptions += ($config.libraylib.opengl_debug_context ? -DRLGL_ENABLE_OPENGL_DEBUG_CONTEXT=1 : -DRLGL_ENABLE_OPENGL_DEBUG_CONTEXT=0)
c.poptions += ($config.libraylib.show_gl_details_info ? -DRLGL_SHOW_GL_DETAILS_INFO=1       : -DRLGL_SHOW_GL_DETAILS_INFO=0)

# rshapes
#
c.poptions += ($config.libraylib.quads_draw_mode ? -DSUPPORT_QUADS_DRAW_MODE=1 : -DSUPPORT_QUADS_DRAW_MODE=0)

# rtextures
#
c.poptions += ($config.libraylib.fileformat_png  ? -DSUPPORT_FILEFORMAT_PNG=1  : -DSUPPORT_FILEFORMAT_PNG=0)
c.poptions += ($config.libraylib.fileformat_bmp  ? -DSUPPORT_FILEFORMAT_BMP=1  : -DSUPPORT_FILEFORMAT_BMP=0)
c.poptions += ($config.libraylib.fileformat_tga  ? -DSUPPORT_FILEFORMAT_TGA=1  : -DSUPPORT_FILEFORMAT_TGA=0)
c.poptions += ($config.libraylib.fileformat_jpg  ? -DSUPPORT_FILEFORMAT_JPG=1  : -DSUPPORT_FILEFORMAT_JPG=0)
c.poptions += ($config.libraylib.fileformat_gif  ? -DSUPPORT_FILEFORMAT_GIF=1  : -DSUPPORT_FILEFORMAT_GIF=0)
c.poptions += ($config.libraylib.fileformat_qoi  ? -DSUPPORT_FILEFORMAT_QOI=1  : -DSUPPORT_FILEFORMAT_QOI=0)
c.poptions += ($config.libraylib.fileformat_psd  ? -DSUPPORT_FILEFORMAT_PSD=1  : -DSUPPORT_FILEFORMAT_PSD=0)
c.poptions += ($config.libraylib.fileformat_dds  ? -DSUPPORT_FILEFORMAT_DDS=1  : -DSUPPORT_FILEFORMAT_DDS=0)
c.poptions += ($config.libraylib.fileformat_hdr  ? -DSUPPORT_FILEFORMAT_HDR=1  : -DSUPPORT_FILEFORMAT_HDR=0)
c.poptions += ($config.libraylib.fileformat_pic  ? -DSUPPORT_FILEFORMAT_PIC=1  : -DSUPPORT_FILEFORMAT_PIC=0)
c.poptions += ($config.libraylib.fileformat_pnm  ? -DSUPPORT_FILEFORMAT_PNM=1  : -DSUPPORT_FILEFORMAT_PNM=0)
c.poptions += ($config.libraylib.fileformat_ktx  ? -DSUPPORT_FILEFORMAT_KTX=1  : -DSUPPORT_FILEFORMAT_KTX=0)
c.poptions += ($config.libraylib.fileformat_astc ? -DSUPPORT_FILEFORMAT_ASTC=1 : -DSUPPORT_FILEFORMAT_ASTC=0)
c.poptions += ($config.libraylib.fileformat_pkm  ? -DSUPPORT_FILEFORMAT_PKM=1  : -DSUPPORT_FILEFORMAT_PKM=0)
c.poptions += ($config.libraylib.fileformat_pvr  ? -DSUPPORT_FILEFORMAT_PVR=1  : -DSUPPORT_FILEFORMAT_PVR=0)
c.poptions += ($config.libraylib.image_export     ? -DSUPPORT_IMAGE_EXPORT=1     : -DSUPPORT_IMAGE_EXPORT=0)
c.poptions += ($config.libraylib.image_generation ? -DSUPPORT_IMAGE_GENERATION=1 : -DSUPPORT_IMAGE_GENERATION=0)

# rtext
#
c.poptions += ($config.libraylib.fileformat_ttf ? -DSUPPORT_FILEFORMAT_TTF=1 : -DSUPPORT_FILEFORMAT_TTF=0)
c.poptions += ($config.libraylib.fileformat_fnt ? -DSUPPORT_FILEFORMAT_FNT=1 : -DSUPPORT_FILEFORMAT_FNT=0)
c.poptions += ($config.libraylib.fileformat_bdf ? -DSUPPORT_FILEFORMAT_BDF=1 : -DSUPPORT_FILEFORMAT_BDF=0)

# rmodels
#
c.poptions += ($config.libraylib.fileformat_obj  ? -DSUPPORT_FILEFORMAT_OBJ=1  : -DSUPPORT_FILEFORMAT_OBJ=0)
c.poptions += ($config.libraylib.fileformat_mtl  ? -DSUPPORT_FILEFORMAT_MTL=1  : -DSUPPORT_FILEFORMAT_MTL=0)
c.poptions += ($config.libraylib.fileformat_iqm  ? -DSUPPORT_FILEFORMAT_IQM=1  : -DSUPPORT_FILEFORMAT_IQM=0)
c.poptions += ($config.libraylib.fileformat_gltf ? -DSUPPORT_FILEFORMAT_GLTF=1 : -DSUPPORT_FILEFORMAT_GLTF=0)
c.poptions += ($config.libraylib.fileformat_vox  ? -DSUPPORT_FILEFORMAT_VOX=1  : -DSUPPORT_FILEFORMAT_VOX=0)
c.poptions += ($config.libraylib.fileformat_m3d  ? -DSUPPORT_FILEFORMAT_M3D=1  : -DSUPPORT_FILEFORMAT_M3D=0)
c.poptions += ($config.libraylib.mesh_generation ? -DSUPPORT_MESH_GENERATION=1 : -DSUPPORT_MESH_GENERATION=0)
c.poptions += ($config.libraylib.gpu_skinning    ? -DSUPPORT_GPU_SKINNING=1    : -DSUPPORT_GPU_SKINNING=0)

# raudio
#
c.poptions += ($config.libraylib.fileformat_wav  ? -DSUPPORT_FILEFORMAT_WAV=1  : -DSUPPORT_FILEFORMAT_WAV=0)
c.poptions += ($config.libraylib.fileformat_ogg  ? -DSUPPORT_FILEFORMAT_OGG=1  : -DSUPPORT_FILEFORMAT_OGG=0)
c.poptions += ($config.libraylib.fileformat_mp3  ? -DSUPPORT_FILEFORMAT_MP3=1  : -DSUPPORT_FILEFORMAT_MP3=0)
c.poptions += ($config.libraylib.fileformat_qoa  ? -DSUPPORT_FILEFORMAT_QOA=1  : -DSUPPORT_FILEFORMAT_QOA=0)
c.poptions += ($config.libraylib.fileformat_flac ? -DSUPPORT_FILEFORMAT_FLAC=1 : -DSUPPORT_FILEFORMAT_FLAC=0)
c.poptions += ($config.libraylib.fileformat_xm   ? -DSUPPORT_FILEFORMAT_XM=1   : -DSUPPORT_FILEFORMAT_XM=0)
c.poptions += ($config.libraylib.fileformat_mod  ? -DSUPPORT_FILEFORMAT_MOD=1  : -DSUPPORT_FILEFORMAT_MOD=0)

if ($c.target.class == 'windows')
{
  c.poptions += -D_CRT_SECURE_NO_WARNINGS -DUNICODE -D_UNICODE

  # GLFW/glad and Windows headers both define APIENTRY.
  #
  if ($c.id == 'msvc')
    c.coptions += /wd4005
}
else
{
  c.poptions += -D_GNU_SOURCE
}

# Bundled GLFW display backends (Linux only).
#
if (!$config.libraylib.external_glfw && $c.target.class == 'linux')
{
  if (!$config.libraylib.glfw_x11 && !$config.libraylib.glfw_wayland)
    fail "config.libraylib.glfw_x11 and/or config.libraylib.glfw_wayland \
must be true when using bundled GLFW on Linux"

  if $config.libraylib.glfw_x11
    c.poptions += -D_GLFW_X11

  if $config.libraylib.glfw_wayland
    c.poptions += -D_GLFW_WAYLAND
}

# Upstream RLAPI export macros (shared library only). Hide non-RLAPI
# symbols so bundled GLFW does not leak into the shared library ABI.
#
objs{*}: c.poptions += -DBUILD_LIBTYPE_SHARED
if ($c.target.class != 'windows')
  objs{*}: c.coptions += -fvisibility=hidden

# rglfw.c includes Objective-C sources on macOS.
#
if ($c.target.class == 'macos' && !$config.libraylib.external_glfw)
  c{rglfw}: c.coptions += -x objective-c

# ---------------------------------------------------------------------------
# System libraries
# ---------------------------------------------------------------------------
#
switch $c.target.class, $c.target.system
{
  case 'windows', 'mingw32'
  {
    c.libs += -lopengl32 -lgdi32 -lwinmm
  }
  case 'windows'
  {
    c.libs += opengl32.lib gdi32.lib winmm.lib shell32.lib user32.lib
  }
  case 'macos'
  {
    c.libs += -framework OpenGL -framework Cocoa -framework IOKit \
              -framework CoreVideo -framework CoreAudio
  }
  case 'linux'
  {
    c.libs += -lGL -lm -lpthread -ldl -lrt

    if (!$config.libraylib.external_glfw)
    {
      if $config.libraylib.glfw_x11
        c.libs += -lX11

      if $config.libraylib.glfw_wayland
        c.libs += -lwayland-client -lwayland-cursor -lwayland-egl -lxkbcommon
    }
  }
  default
  {
    if ($c.target.class != 'windows')
      c.libs += -lm -lpthread
  }
}

# ---------------------------------------------------------------------------
# Export options and metadata
# ---------------------------------------------------------------------------
#
# Include path is common. USE_LIBTYPE_SHARED is only for the shared variant so
# consumers get RLAPI as dllimport (matches upstream CMake INSTALL_INTERFACE).
#
lib{raylib}:
{
  c.export.poptions = "-I$src_base"
  c.export.libs = $intf_libs

  export.metadata = 1 libraylib

  libraylib.graphics          = [string] $config.libraylib.graphics
  libraylib.external_glfw     = [bool] $config.libraylib.external_glfw
  libraylib.module_shapes     = [bool] $config.libraylib.module_shapes
  libraylib.module_textures   = [bool] $config.libraylib.module_textures
  libraylib.module_text       = [bool] $config.libraylib.module_text
  libraylib.module_models     = [bool] $config.libraylib.module_models
  libraylib.module_audio      = [bool] $config.libraylib.module_audio
}

libs{raylib}: c.export.poptions += -DUSE_LIBTYPE_SHARED

# Propagate system libraries that consumers need when linking.
#
switch $c.target.class, $c.target.system
{
  case 'windows', 'mingw32'
    lib{raylib}: c.export.libs += -lopengl32 -lgdi32 -lwinmm
  case 'windows'
    lib{raylib}: c.export.libs += opengl32.lib gdi32.lib winmm.lib shell32.lib user32.lib
  case 'macos'
    lib{raylib}: c.export.libs += -framework OpenGL -framework Cocoa \
                                  -framework IOKit -framework CoreVideo \
                                  -framework CoreAudio
  case 'linux'
  {
    lib{raylib}: c.export.libs += -lGL -lm -lpthread -ldl -lrt

    if (!$config.libraylib.external_glfw)
    {
      if $config.libraylib.glfw_x11
        lib{raylib}: c.export.libs += -lX11

      if $config.libraylib.glfw_wayland
        lib{raylib}: c.export.libs += -lwayland-client -lwayland-cursor \
                                      -lwayland-egl -lxkbcommon
    }
  }
  default
  {
    if ($c.target.class != 'windows')
      lib{raylib}: c.export.libs += -lm -lpthread
  }
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{raylib}: bin.lib.version = "-$version.project_id"
else
  lib{raylib}: bin.lib.version = "-$version.major.$version.minor"

# Install public headers flat into include/ (upstream convention:
# #include <raylib.h>). Do not install private headers.
#
h{*}: install = false

h{raylib}@./:  install = include/
h{raymath}@./: install = include/
h{rlgl}@./:    install = include/
h{rcamera}@./: install = include/
